apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-react-app
spec:
  replicas: 2
  selector: 
    matchLabels: 
      app: my-react-app
  template:
    metadata:
      labels:
        app: my-react-app
    spec:
      containers: 
        - name: my-react-app
          image: docker.io/ajajmal/my-react-app:latest
          ports: 
            - containerPort: 80
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
